name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: d4844aaf-4533-4d72-80df-65806ecb6591
      NPM_AUTH_TOKEN: ${{ secrets.QMBOT_NPM_TOKEN }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install packages
        run: yarn
      - name: run linter
        run: yarn lint
      - name: build bundles
        run: yarn build
      - name: run tests
        run: yarn test
      - name: upload coverage
        run: bash <(curl -s https://codecov.io/bash)

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.5
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          publish_command: ./publish
        env:
          GITHUB_TOKEN: ${{ secrets.QMBOT_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.QMBOT_NPM_TOKEN }}
