name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: d4844aaf-4533-4d72-80df-65806ecb6591

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install packages
        run: yarn
      - name: run linter
        run: yarn lint
      - name: build bundles
        run: yarn build
      - name: run tests
        run: yarn test
      - name: upload coverage
        run: bash <(curl -s https://codecov.io/bash)
