name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: d4844aaf-4533-4d72-80df-65806ecb6591

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: bash <(curl -s https://codecov.io/bash)
